# Generated by Django 6.1.1 on 2026-09-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.AddField(
            model_name='eventsector',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
